spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # Ensures Hibernate updates the schema
    show-sql: true  # Logs the SQL queries executed by Hibernate
  h2:
    console:
      enabled: true  # Enables H2 console access for debugging
      path: /h2-console  # Path to access H2 console (optional)
